ALTER TABLE `ts_denounce` ADD INDEX `from` ( `from`, `state` );
ALTER TABLE `ts_feed` ADD INDEX `uid` ( `uid` );
ALTER TABLE `ts_login` ADD INDEX `uid` ( `uid` );
ALTER TABLE `ts_notify` ADD INDEX `receive_2` (`receive`, `is_read`);
ALTER TABLE `ts_user_blacklist` ADD INDEX `uid` (`uid`, `fid`);
ALTER TABLE `ts_user_blacklist` ADD INDEX `fid` (`fid`);
ALTER TABLE `ts_user_count` ADD INDEX `atme` (`uid`, `atme`);
ALTER TABLE `ts_user_count` ADD INDEX `comment` (`uid`, `comment`);
ALTER TABLE `ts_user_group_link` ADD INDEX `uid` (`uid`);
ALTER TABLE `ts_weibo` ADD INDEX `uid` (`uid`, `isdel`);
ALTER TABLE `ts_weibo` ADD INDEX `type` (`uid`, `type`);
ALTER TABLE `ts_weibo` ADD INDEX `transpond` (`uid`, `transpond_id`);
ALTER TABLE `ts_weibo` ADD INDEX `ctime` (`ctime`);
ALTER TABLE `ts_weibo_atme` ADD INDEX `weibo_id` (`weibo_id`, `uid`);
ALTER TABLE `ts_weibo_atme` ADD INDEX `uid_2` (`uid`);
ALTER TABLE `ts_weibo_comment` ADD INDEX `weibo_id` (`weibo_id`);
ALTER TABLE `ts_weibo_follow` ADD INDEX `uid_2` (`uid`, `fid`, `type`);
ALTER TABLE `ts_weibo_topic` ADD INDEX `count` (`count`);
ALTER TABLE `ts_weibo_topic` ADD INDEX `name` (`name`, `count`);